Warehousing/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('warehouse.urls')),
    # drf-spectacular schema and documentation
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

warehouse/urls.py
from django.urls import path

from warehouse.views import PhoneCreateView, ColorCreateView, BrandCreateView, PhoneListAPIView, CountryCreateView, \
    SimilarityPhoneListAPIView

app_name = 'phone'
urlpatterns = [
    path('api/phones/', PhoneListAPIView.as_view(), name='api-phones'),

    path('', PhoneCreateView.as_view(), name='add'),
    path('add-color/', ColorCreateView.as_view(), name='color_add'),
    path('add-brand/', BrandCreateView.as_view(), name='brand_add'),
    path('add-country/', CountryCreateView.as_view(), name='country_add'),
    path('similarity-phones/', SimilarityPhoneListAPIView.as_view(), name='similarity_phones'),
]

templates/inclodes/footer.html
{% load static %}

<script src="{% static 'js/site.js' %}"></script>
{#<script src="{% static 'js/jquery.min.js' %}"></script>#}
{#<script src="{% static 'js/jquery.easing.min.js' %}"></script>#}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{% static 'js/mdb.umd.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


templates/inclodes/head.html
{% load static %}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#     <meta name="csrf-token" content="{{ csrf_token }}">#}
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.min.css" rel="stylesheet">#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"#}
{#        integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="#}
{#        crossorigin="anonymous" referrerpolicy="no-referrer" />#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/fontawesome.min.css"#}
{#        integrity="sha512-UuQ/zJlbMVAw/UU8vVBhnI4op+/tFOpQZVT+FormmIEhRSCnJWyHiBbEVgM4Uztsht41f3FzVWgLuwzUqOObKw=="#}
{#        crossorigin="anonymous" referrerpolicy="no-referrer" />#}
{#    <link rel="stylesheet" href="{% static 'css/style.css' %}">#}
{#    <title>Dashboard</title>#}
{#</head>#}

<meta charset="UTF-8">
<meta name="csrf-token" content="{{ csrf_token }}">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
<link rel="stylesheet" href="{% static 'css/all.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/style.css' %}">



templates/inclodes/header.html
{% load static %}
<!-- Header -->
<header class="header-dashboard container-fluid">

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>

                    {% if 'success' in message.tags %}

                        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                            <g id="SVGRepo_iconCarrier">
                                <path opacity="0.4"
                                      d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                                      fill="#23a931"></path>
                                <path d="M10.5795 15.5801C10.3795 15.5801 10.1895 15.5001 10.0495 15.3601L7.21945 12.5301C6.92945 12.2401 6.92945 11.7601 7.21945 11.4701C7.50945 11.1801 7.98945 11.1801 8.27945 11.4701L10.5795 13.7701L15.7195 8.6301C16.0095 8.3401 16.4895 8.3401 16.7795 8.6301C17.0695 8.9201 17.0695 9.4001 16.7795 9.6901L11.1095 15.3601C10.9695 15.5001 10.7795 15.5801 10.5795 15.5801Z"
                                      fill="#23a931"></path>
                            </g>
                        </svg>
                    {% else %}
                        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                            <g id="SVGRepo_iconCarrier">
                                <path opacity="0.4"
                                      d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                                      fill="#ee0b0b"></path>
                                <path d="M13.0594 12.0001L15.3594 9.70011C15.6494 9.41011 15.6494 8.93011 15.3594 8.64011C15.0694 8.35011 14.5894 8.35011 14.2994 8.64011L11.9994 10.9401L9.69937 8.64011C9.40937 8.35011 8.92937 8.35011 8.63938 8.64011C8.34938 8.93011 8.34938 9.41011 8.63938 9.70011L10.9394 12.0001L8.63938 14.3001C8.34938 14.5901 8.34938 15.0701 8.63938 15.3601C8.78938 15.5101 8.97937 15.5801 9.16937 15.5801C9.35937 15.5801 9.54937 15.5101 9.69937 15.3601L11.9994 13.0601L14.2994 15.3601C14.4494 15.5101 14.6394 15.5801 14.8294 15.5801C15.0194 15.5801 15.2094 15.5101 15.3594 15.3601C15.6494 15.0701 15.6494 14.5901 15.3594 14.3001L13.0594 12.0001Z"
                                      fill="#ee0b0b"></path>
                            </g>
                        </svg>
                    {% endif %}
                    {{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="row nav-parent m-0">
        <div class="col-lg-2 col-4 p-0 p-lg-2 menu-bar-parent">
            <!-- Use any element to open the sidenav -->
            <button id="OpenNavBtn" class="openNavBtn d-block d-lg-none">
                <svg fill="" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24.75 24.75" xml:space="preserve"
                     stroke="">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                            <g>
                                <path
                                        d="M0,3.875c0-1.104,0.896-2,2-2h20.75c1.104,0,2,0.896,2,2s-0.896,2-2,2H2C0.896,5.875,0,4.979,0,3.875z M22.75,10.375H2 c-1.104,0-2,0.896-2,2c0,1.104,0.896,2,2,2h20.75c1.104,0,2-0.896,2-2C24.75,11.271,23.855,10.375,22.75,10.375z M22.75,18.875H2 c-1.104,0-2,0.896-2,2s0.896,2,2,2h20.75c1.104,0,2-0.896,2-2S23.855,18.875,22.75,18.875z">
                                </path>
                            </g>
                        </g>
                    </svg>
            </button>
            <div class="header-page-title">
                {{ current_page }}
            </div>
        </div>

    </div>
</header><!-- Header -->

templates/inclodes/navbar.html
{% load static %}
<!-- Sidebar Section -->
<section id="mySidenav" class="mysidenav-menu">
    <a href="javascript:void(0)" class="closeNavbtn d-block d-lg-none">&times;</a>
    <h4 class="text-white text-center w-100">SideMenu</h4>
    <ul class="row side-menu-parent">
        <li class="side-menu-item {% if current_page == 'add phone' %}active{% endif %}">
            <a href="{% url 'phone:add' %}">
                <svg fill="" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="dashboard"
                     class="icon glyph" stroke="">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <rect x="2" y="2" width="9" height="11" rx="2"></rect>
                        <rect x="13" y="2" width="9" height="7" rx="2"></rect>
                        <rect x="2" y="15" width="9" height="7" rx="2"></rect>
                        <rect x="13" y="11" width="9" height="11" rx="2"></rect>
                    </g>
                </svg>
                add phone
            </a>
        </li>
        <li class="side-menu-item {% if current_page == 'add color' %}active{% endif %}">
            <a href="{% url 'phone:color_add' %}">
                <svg fill="" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="dashboard"
                     class="icon glyph" stroke="">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <rect x="2" y="2" width="9" height="11" rx="2"></rect>
                        <rect x="13" y="2" width="9" height="7" rx="2"></rect>
                        <rect x="2" y="15" width="9" height="7" rx="2"></rect>
                        <rect x="13" y="11" width="9" height="11" rx="2"></rect>
                    </g>
                </svg>
                add color
            </a>
        </li>
        <li class="side-menu-item {% if current_page == 'add brand' %}active{% endif %}">
            <a href="{% url 'phone:brand_add' %}">
                <svg fill="" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="dashboard"
                     class="icon glyph" stroke="">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <rect x="2" y="2" width="9" height="11" rx="2"></rect>
                        <rect x="13" y="2" width="9" height="7" rx="2"></rect>
                        <rect x="2" y="15" width="9" height="7" rx="2"></rect>
                        <rect x="13" y="11" width="9" height="11" rx="2"></rect>
                    </g>
                </svg>
                add brand
            </a>
        </li>
        <li class="side-menu-item {% if current_page == 'add country' %}active{% endif %}">
            <a href="{% url 'phone:country_add' %}">
                <svg fill="" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="dashboard"
                     class="icon glyph" stroke="">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <rect x="2" y="2" width="9" height="11" rx="2"></rect>
                        <rect x="13" y="2" width="9" height="7" rx="2"></rect>
                        <rect x="2" y="15" width="9" height="7" rx="2"></rect>
                        <rect x="13" y="11" width="9" height="11" rx="2"></rect>
                    </g>
                </svg>
                add country
            </a>
        </li>
        <li class="side-menu-item ">
            <a href="/api/docs">
                <svg fill="" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="dashboard"
                     class="icon glyph" stroke="">
                    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                    <g id="SVGRepo_iconCarrier">
                        <rect x="2" y="2" width="9" height="11" rx="2"></rect>
                        <rect x="13" y="2" width="9" height="7" rx="2"></rect>
                        <rect x="2" y="15" width="9" height="7" rx="2"></rect>
                        <rect x="13" y="11" width="9" height="11" rx="2"></rect>
                    </g>
                </svg>
                report page
            </a>
        </li>


    </ul>
</section>
<!-- Sidebar Section -->